import PDFDocument from 'pdfkit';

export const generateInvoicePDF = async (invoiceData) => {
  try {
    console.log('Generating PDF for invoice:', invoiceData.invoiceNumber);

    const {
      invoiceNumber,
      kotId,
      user,
      deliveryAddress,
      items,
      subtotal,
      tax,
      total,
      createdAt
    } = invoiceData;

    console.log('Creating PDF document...');

    // Create PDF document
    const doc = new PDFDocument({
      size: 'A4',
      margin: 50
    });

    const buffers = [];
    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => {
      console.log('PDF generation completed');
    });
    doc.on('error', (err) => {
      console.error('PDF generation error:', err);
    });

    // Company Header
    doc.fontSize(24).font('Helvetica-Bold').text('PrimeOps', { align: 'center' });
    doc.fontSize(12).font('Helvetica').text('AI-Powered Kitchen Order Ticket & Inventory Engine', { align: 'center' });
    doc.moveDown(2);

    // Invoice Title
    doc.fontSize(18).font('Helvetica-Bold').text('INVOICE', { align: 'center' });
    doc.moveDown();

    // Invoice Details
    doc.fontSize(12).font('Helvetica');
    doc.text(`Invoice Number: ${invoiceNumber}`);
    doc.text(`Date: ${createdAt.toLocaleDateString()}`);
    doc.text(`Time: ${createdAt.toLocaleTimeString()}`);
    doc.text(`KOT ID: ${kotId || 'N/A'}`);
    doc.moveDown();

    // Invoice Details
    doc.fontSize(14).font('Helvetica-Bold').text('Invoice Details:', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12).font('Helvetica');
    doc.text(`Invoice Number: ${invoiceNumber}`);
    doc.text(`Date: ${createdAt.toLocaleDateString()}`);
    doc.moveDown();

    // Customer Details (from user profile stored in DB)
    doc.fontSize(14).font('Helvetica-Bold').text('Bill To:', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12).font('Helvetica');
    doc.text(`Name: ${user.name}`);
    doc.text(`Phone: ${user.phone}`);
    doc.text(`Email: ${user.email}`);
    doc.moveDown();

    // Delivery Address (entered during checkout)
    doc.fontSize(14).font('Helvetica-Bold').text('Delivery Address:', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12).font('Helvetica');
    doc.text(deliveryAddress);
    doc.moveDown();

    // Items Table Header
    const tableTop = doc.y;
    doc.fontSize(12).font('Helvetica-Bold');
    doc.text('Item', 50, tableTop);
    doc.text('Qty', 300, tableTop);
    doc.text('Unit Price', 350, tableTop);
    doc.text('Total', 450, tableTop);

    // Table line
    doc.moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).stroke();
    doc.moveDown();

    // Items (from order data)
    let y = tableTop + 25;
    doc.font('Helvetica');
    items.forEach(item => {
      const name = item.dish ? item.dish.name : item.name;
      const price = item.dish ? item.dish.price : item.price;
      doc.text(name, 50, y);
      doc.text(item.quantity.toString(), 300, y);
      doc.text(`$${parseFloat(price).toFixed(2)}`, 350, y);
      doc.text(`₹${(price * item.quantity).toFixed(2)}`, 450, y);
      y += 20;
    });

    // Totals (calculated server-side)
    y += 10;
    doc.moveTo(350, y).lineTo(550, y).stroke();
    y += 10;

    doc.font('Helvetica-Bold');
    doc.text('Subtotal:', 350, y);
    doc.text(`₹${parseFloat(subtotal).toFixed(2)}`, 450, y);
    y += 20;

    doc.text('Tax (18%):', 350, y);
    doc.text(`$${parseFloat(tax).toFixed(2)}`, 450, y);
    y += 20;

    doc.text('Total:', 350, y);
    doc.text(`₹${parseFloat(total).toFixed(2)}`, 450, y);

    // Footer
    doc.moveDown(3);
    doc.fontSize(10).font('Helvetica');
    doc.text('Thank you for your business!', { align: 'center' });
    doc.text('Generated by PrimeOps System', { align: 'center' });

    doc.end();

    return new Promise((resolve, reject) => {
      doc.on('end', () => {
        console.log('PDF buffer created, size:', buffers.length);
        const pdfBuffer = Buffer.concat(buffers);
        resolve(pdfBuffer);
      });
      doc.on('error', reject);
    });

  } catch (error) {
    console.error('Error generating PDF:', error);
    throw error;
  }
};


